all: listaParametros punteros words

listaParametros: listaParametros.c
	gcc -o listaParametros listaParametros.c
punteros: punteros.c
	gcc -o punteros punteros.c
words: words.c
	gcc -o words words.c

clean:
	rm listaParametros
	rm punteros
	rm words