/* Main.c file generated by New Project wizard
 *
 * Created:   do. oct. 15 2023
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h> 
#include <stdlib.h>
#include "config.h"



#define _XTAL_FREQ 8000000

int count = 1;
int num = 0;
char caracters[4] = {0x3F, 0x3F, 0x3F, 0x3F};
char numbers_code[10] = {0x3F, 0x06, 0x5B, 0x4F, 0x66, 0x6D, 0x7D, 0x07, 0x7F, 0x67};


void interrupt RSI_high() {
   if (INT0IE && INT0IF) {
      num = rand()%10000;
      int aux = num;
      for (int i = 0; i < 4; ++i) {
         caracters[i] = numbers_code[aux%10];
         aux /= 10;
      }
      GIEL = 1;
      INT0IF = 0;
   }
}

void interrupt low_priority RSI_low() {
   if (INT1IE && INT1IF) {
      num += count;
      int aux = num;
      for (int i = 0; i < 4; ++i) {
         caracters[i] = numbers_code[aux%10];
         aux /= 10;
      }
      INT1IF = 0;
   }
   if (INT2IE && INT2IF) {
      count *= 10;
      if (count == 10000) count = 1;
      INT2IF = 0;
   }
}

void display_char(unsigned char displays, int num) {
   
   PORTA = 0x00;
   PORTD = 0x00;
   PORTA = displays;
   PORTD = num;  
   __delay_us(20);
}

void imprimir_num() {
   display_char(0x01, caracters[0]);
   display_char(0x02, caracters[0]);
   display_char(0x04, caracters[0]);
   display_char(0x08, caracters[0]);
}


void configure_pic() {
   // Output (seleccio display).
   ANSELA = 0x0;
   TRISA = 0x0; 
   
   // Output (segments display).
   ANSELD = 0x00;
   TRISD = 0x00;
   
   // Input (botons).
   ANSELB = 0x00;
   TRISB = 0x07;
   
   //Interrup
   INT0IF = 0;    //Flags a 0
   INT0IE = 1;    //Int 0 activades
   INTEDG0 = 1;   //Flanc de pujada

   INT1IP = 0;    //Low prio
   INT1IF = 0;    //Flags a 0
   INT1IE = 1;    //Int 1 activada
   INTEDG1 = 0;   //Flanc de baixada

   INT2IP = 0;    //Low prio
   INT2IF = 0;    //Flags = 0
   INT2IE = 1;    //Int 2 activada
   INTEDG2 = 0;   //Flanc de baixada

   IPEN = 1;      //Habilitem les prioritats
   GIEH = 1;      //alta prio activat
   GIEL = 0;      //baixa prio desactivada

}


void main(void) {
   configure_pic();
   int contador = 0;
   
   
   while (1) {
      srand(contador);
      if (contador == 2000) {
	      contador = 0;
      }      
      imprimir_num();   
      ++contador;    
   }
}