all: busqueda_parcial busqueda_parcial_con_espera busqueda_multiple

busqueda_parcial: busqueda_parcial.c
	gcc -o busqueda_parcial busqueda_parcial.c

busqueda_parcial_con_espera: busqueda_parcial_con_espera.c
	gcc -o busqueda_parcial_con_espera busqueda_parcial_con_espera.c

busqueda_multiple: busqueda_multiple.c
	gcc -o busqueda_multiple busqueda_multiple.c

clean:
	rm -f busqueda_parcial_con_espera busqueda_multiple busqueda_parcial