CREATE TABLE DEPARTAMENTS
         (	NUM_DPT INTEGER,
	NOM_DPT CHAR(20),
	PLANTA INTEGER,
	EDIFICI CHAR(30),
	CIUTAT_DPT CHAR(20),
	PRIMARY KEY (NUM_DPT));

CREATE TABLE PROJECTES
         (	NUM_PROJ INTEGER,
	NOM_PROJ CHAR(10),
	PRODUCTE CHAR(20),
	PRESSUPOST INTEGER,
	PRIMARY KEY (NUM_PROJ));

CREATE TABLE EMPLEATS
         (	NUM_EMPL INTEGER,
	NOM_EMPL CHAR(30),
	SOU INTEGER,
	CIUTAT_EMPL CHAR(20),
	NUM_DPT INTEGER,
	NUM_PROJ INTEGER,
	PRIMARY KEY (NUM_EMPL),
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT),
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ));
	
	
INSERT INTO  DEPARTAMENTS VALUES (2,'MARKETING',3,'RIOS ROSAS','ZAMORA');
INSERT INTO  EMPLEATS VALUES (3,'ROBERTO',25000,'ZAMORA',2, NULL);

SELECT D.NUM_DPT, COUNT(E.NUM_EMPL) as NUM_EMPLEATS
FROM DEPARTAMENTS D
LEFT JOIN EMPLEATS E ON D.CIUTAT_DPT = E.CIUTAT_EMPL
GROUP BY D.NUM_DPT
ORDER BY D.NUM_DPT;
