CREATE TABLE DEPARTAMENTS
         (	NUM_DPT INTEGER,
	NOM_DPT CHAR(20),
	PLANTA INTEGER,
	EDIFICI CHAR(30),
	CIUTAT_DPT CHAR(20),
	PRIMARY KEY (NUM_DPT));

CREATE TABLE PROJECTES
         (	NUM_PROJ INTEGER,
	NOM_PROJ CHAR(10),
	PRODUCTE CHAR(20),
	PRESSUPOST INTEGER,
	PRIMARY KEY (NUM_PROJ));

CREATE TABLE EMPLEATS
         (	NUM_EMPL INTEGER,
	NOM_EMPL CHAR(30),
	SOU INTEGER,
	CIUTAT_EMPL CHAR(20),
	NUM_DPT INTEGER,
	NUM_PROJ INTEGER,
	PRIMARY KEY (NUM_EMPL),
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT),
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ));


INSERT INTO DEPARTAMENTS VALUES (2, NULL, NULL, NULL,'Barcelona');
INSERT INTO DEPARTAMENTS VALUES (3, NULL, NULL, NULL, NULL);

INSERT INTO  EMPLEATS VALUES (3, NULL, NULL, 'Barcelona', 2, NULL);
INSERT INTO  EMPLEATS VALUES (4, NULL, NULL, 'Madrid', 2, NULL);

SELECT d.CIUTAT_DPT AS CIUTAT, count(e.NUM_EMPL) AS COUNT
FROM DEPARTAMENTS d 
LEFT JOIN EMPLEATS e ON d.NUM_DPT = e.NUM_DPT
WHERE d.CIUTAT_DPT IS NOT NULL
GROUP BY d.CIUTAT_DPT

UNION

SELECT e.CIUTAT_EMPL AS CIUTAT, 0 AS COUNT
FROM EMPLEATS e 
LEFT JOIN DEPARTAMENTS d ON d.CIUTAT_DPT = e.CIUTAT_EMPL
WHERE d.NUM_DPT IS NULL AND e.CIUTAT_EMPL IS NOT NULL
GROUP BY e.CIUTAT_EMPL

ORDER BY CIUTAT;

commit;