(define lista '(1 2 3 4 5))
(display "Original list: ")
(display lista)
(newline)
(display "First element: ")
(display (car lista))
(newline)
(display "Rest of the list: ")
(display (cdr lista))
(newline)
(display "Add an element to the list: ")
(display (cons 0 lista))
(newline)
(display "Empty list? ")
(display (null? lista))
(newline)